version: '3.9'

services:

  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_web
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=django
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5    

volumes:
  postgres_data:
  media_volume:
  static_volume: