# Generated by Django 6.0.3 on 2026-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_size_alter_product_brand_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
