# Generated by Django 6.0.3 on 2026-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
